// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	domain "github.com/n-r-w/agent-standards-mcp/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStandardLoader is a mock of StandardLoader interface.
type MockStandardLoader struct {
	ctrl     *gomock.Controller
	recorder *MockStandardLoaderMockRecorder
	isgomock struct{}
}

// MockStandardLoaderMockRecorder is the mock recorder for MockStandardLoader.
type MockStandardLoaderMockRecorder struct {
	mock *MockStandardLoader
}

// NewMockStandardLoader creates a new mock instance.
func NewMockStandardLoader(ctrl *gomock.Controller) *MockStandardLoader {
	mock := &MockStandardLoader{ctrl: ctrl}
	mock.recorder = &MockStandardLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStandardLoader) EXPECT() *MockStandardLoaderMockRecorder {
	return m.recorder
}

// GetStandards mocks base method.
func (m *MockStandardLoader) GetStandards(ctx context.Context, standardNames []string) ([]domain.Standard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStandards", ctx, standardNames)
	ret0, _ := ret[0].([]domain.Standard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStandards indicates an expected call of GetStandards.
func (mr *MockStandardLoaderMockRecorder) GetStandards(ctx, standardNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStandards", reflect.TypeOf((*MockStandardLoader)(nil).GetStandards), ctx, standardNames)
}

// ListStandards mocks base method.
func (m *MockStandardLoader) ListStandards(ctx context.Context) ([]domain.StandardInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStandards", ctx)
	ret0, _ := ret[0].([]domain.StandardInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStandards indicates an expected call of ListStandards.
func (mr *MockStandardLoaderMockRecorder) ListStandards(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStandards", reflect.TypeOf((*MockStandardLoader)(nil).ListStandards), ctx)
}
